apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-secret-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8ssecretdemo
  template:
    metadata:
      labels:
        app: k8ssecretdemo
    spec:
      containers:
        - name: k8ssecretdemo
          image: ezehiga/k8ssecretdemo:latest
          imagePullPolicy: Never
          env:
          - name: secret
            valueFrom:
              secretKeyRef:
                name: k8ssecret
                key: secret
---
apiVersion: v1
kind: Service
metadata:
  name: k8sloadbalancer
spec:
  type: LoadBalancer
  selector:
    app: k8ssecretdemo
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: k8ssecretdemo
